In [ ]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6]])
print("array is of type:",type(a))
print("no. dimension:",a.ndim)
print("shape of array is:",a.shape)
print("size of array is:",a.size)
print("type of array:",a.dtype)


array is of type: <class 'numpy.ndarray'>
no. dimension: 2
shape of array is: (2, 3)
size of array is: 6
type of array: int64


In [ ]:
import numpy as np
a=np.array([1,2,3])
print("array with rank 1:\n",a)
a=np.array([[1,2,3],[3,4,5]])
print("array with rank 2:",a)
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
print("array with rank 3:",a)
a=np.array((1,2,3))
print("array created using passed tupple:",a)


array with rank 1:
 [1 2 3]
array with rank 2: [[1 2 3]
 [3 4 5]]
array with rank 3: [[1 2 3]
 [3 4 5]
 [6 7 8]]
array created using passed tupple: [1 2 3]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=a.copy()
print(a)
print("id of a",id(a))
print("id of c",id(b))
a[0]=13
print("original array",a)
print("copy",b)


[1 2 3 4 5 6]
id of a 132432196001040
id of c 132432195998832
original array [13  2  3  4  5  6]
copy [1 2 3 4 5 6]


In [ ]:
def sum(array):
  sum=0
  for i in array:
    sum+=i
  return sum                                            # for and return sholud in same len if not then it will no diplay
a=[1,4,5,6]
print("sum of numbers is"+str(sum(a)))

sum of numbers is16


In [ ]:
import numpy as np
a=np.arange(90,5,-8)
          #(start from,at the end range,divisible or gap)
print("a sequential array with a negative step :",a)

b=a[np.array([3,1,2])]
                  #o,1,2,3
                  #(at what place like 3 pa 66 )
print("elements at these indices are",b)

a sequential array with a negative step : [90 82 74 66 58 50 42 34 26 18 10]
elements at these indices are [66 82 74]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[1:5])
print(a[4:])
print(a[:5])
print(a[1:7:2])   # fro 1 to 7 at the distance of 2
print(a[::2])      # at dis of 2 all cuz range not given

[2 3 4 5]
[5 6 7]
[1 2 3 4 5]
[2 4 6]
[1 3 5 7]


In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])                                #DID NOT GET ANYTHING
print(a[1,1:4])
print(a[0:2,2])
print(a[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
x=a.copy()
x[0]=42
print(a)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
x=a.view()
a[0]=34
print(a)
print(x)

[34  2  3  4  5]
[34  2  3  4  5]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
x=a.view()
x[0]=34
print(a)
print(x)

[34  2  3  4  5]
[34  2  3  4  5]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
x=a.copy()
y=a.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)

(2, 4)


In [ ]:
import numpy as np
a=np.array([1,2,3,4],ndmin=5)
print(a)
print("shape of array:",a.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newa=a.reshape(4,3)
print(newa)

newa=a.reshape(2,3,2)
print(newa)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy
x=numpy.array([[1,2],[4,5]])
y=numpy.array([[6,7],[8,9]])
print("element wise addd of matrix:")
print(numpy.add(x,y))
print("element wise sub of matrix:")
print(numpy.subtract(x,y))
print("element wise mul of matrix:")
print(numpy.multiply(x,y))
print("element wise div of matrix:")
print(numpy.divide(x,y))

element wise addd of matrix:
[[ 7  9]
 [12 14]]
element wise sub of matrix:
[[-5 -5]
 [-4 -4]]
element wise mul of matrix:
[[ 6 14]
 [32 45]]
element wise div of matrix:
[[0.16666667 0.28571429]
 [0.5        0.55555556]]


In [ ]:
import pandas as pd
mydataset={"cars":["bmw","volvo","ford"],"passings":[3,7,2]}
a=pd.DataFrame(mydataset)
print(myvar)


    cars  passings
0    bmw         3
1  volvo         7
2   ford         2


In [ ]:
import pandas as pd
mydataset={"cars":['bmw','volvo','ford'],"passings":[3,7,2]}
myvar=pd.DataFrame(mydataset)
print(myvar)


    cars  passings
0    bmw         3
1  volvo         7
2   ford         2


In [ ]:
import pandas as pd
print(pd.__version__)

2.0.3


In [ ]:
import pandas as pd
a=[1,7,2]
myvar =pd.Series(a)
print(myvar)
print(myvar[0])

0    1
1    7
2    2
dtype: int64
1


In [ ]:
import pandas as pd
a=[1,5,9]
b=pd.Series(a)          #varchar=b
print(b)
print(b[2])

0    1
1    5
2    9
dtype: int64
9


In [ ]:
import pandas as pd
a=[1,5,9]
b=pd.Series(a,index=["X","Y","Z"])          #varchar=b
print(b)
print(b["Y"])

X    1
Y    5
Z    9
dtype: int64
5


In [ ]:
import pandas as pd
a={"calories":[24,56,59], "duration":[12,4,13]}               #data=a
df=pd.DataFrame(a)
print(df)

print(df.loc[0])

print(df.loc[[0,1]])

   calories  duration
0        24        12
1        56         4
2        59        13
calories    24
duration    12
Name: 0, dtype: int64
   calories  duration
0        24        12
1        56         4


In [ ]:
import pandas as pd                             #NOT WORKING
df=pd.read_csv("Data.csv")
print(df)

In [ ]:
import pandas as pd

print(pd.options.display.max_rows)

60


In [ ]:
#Load a Python Dictionary into a DataFrame   JSON= Python Dictionary
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)


   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


In [ ]:
import pandas as pd
df1 = pd.DataFrame({"fruit" : ["apple", "banana", "avocado"],
					"market_price" : [21, 14, 35]})
display("The first DataFrame")
display(df1)

df2 = pd.DataFrame({"fruit" : ["banana", "apple", "avocado"],
					"wholesaler_price" : [65, 68, 75]})
display("The second DataFrame")
display(df2)
# joining the DataFrames
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")
# how : {‘left’, ‘right’, ‘outer’, ‘inner’}, default ‘inner’

'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35

'The second DataFrame'

fruit  wholesaler_price
0   banana                65
1    apple                68
2  avocado                75

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21                68
1   banana            14                65
2  avocado            35                75

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"fruit" : ["apple", "banana",
                               "avocado", "grape"],
                    "market_price" : [21, 14, 35, 38]})
display("The first DataFrame")
display(df1)
df2 = pd.DataFrame({"fruit" : ["apple", "banana", "grape"],
                    "wholesaler_price" : [65, 68, 71]})
display("The second DataFrame")
display(df2)

# joining the DataFrames
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")

pd.merge(df1, df2, on = "fruit", how = "outer")

'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35
3    grape            38

'The second DataFrame'

fruit  wholesaler_price
0   apple                65
1  banana                68
2   grape                71

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21              65.0
1   banana            14              68.0
2  avocado            35               NaN
3    grape            38              71.0

In [ ]:
#Indentation
j = 1

while(j<= 5):
	print(j)
	j = j + 1

1
2
3
4
5


In [ ]:
i=1
while(i<=5):
  print(i)
  i=i+1

1
2
3
4
5
